### PR TITLE
Issue #104: Fix libdir for aws-c-common dependency

### PR DESCRIPTION
**Pull request by pitrou**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pitrou** [comment]
Please don't merge until I've determined that this actually fixes the issue.

**Comment by jakebolewski** [comment]
We had to do something similar in TileDB with conda (GNUlibdir overriding cmake install dir), so I suspect it will fix the issue.

**Comment by pitrou** [comment]
Ok, this seems to be fixing the issue for me.

**Comment by pitrou** [comment]
Ideally we should check somewhere that `lib64` doesn't get created or populated by the recipe. Unfortunately my bash-fu is weak. Can someone suggest or push the necessary changes?

**Comment by jakebolewski** [comment]
for bash something like:

```
# ensure that /lib64 is not created or populated
if [ -d "${PREFIX}/lib64"]; then
   exit 1
fi
```

at the top of the test.sh should work, I don't know what the windows eqiv. would be off the top of my head.

**Comment by pitrou** [comment]
On top of `run_test.sh` doesn't work, because it checks the entire conda environment and other packages may install in `lib64` (they probably shouldn't, but hey). So I'm adding it in `build.sh` instead.

We don't need to add the same check for Windows because Windows doesn't have the `lib`/`lib64` confusion issue.

**Pull request merged**
