### PR TITLE
No need to bump the minimum deployment target

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by ihnorton** [comment]
Was there an upstream change to fix this? We and @xhochy encountered build errors when targeting 10.9, e.g. https://github.com/conda-forge/aws-sdk-cpp-feedstock/pull/131#issuecomment-697366517

**Review by ihnorton — APPROVED** [review]
Since the build is ok here, I'm assuming that `MACOS_SDK_VERSION` lets the compiler find that missing header? (I can't find where `MACOSX_SDK_VERSION` is actually used though -- don't see it in conda-build, conda-smithy, or cmake).

In any case, LGTM.

**Comment by xhochy** [comment]
@ihnorton @isuruf added docs over at https://github.com/conda-forge/conda-forge.github.io/pull/1181

**Pull request merged**
