### PR TITLE
Bump version to 1.7.143

### PR DESCRIPTION
**Pull request by pitrou**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Also makes the build faster, and tests compiling using CMake.

### CODE REVIEW

**Comment by pitrou** [comment]
@conda-forge/help-c-cpp

**Comment by jakebolewski** [comment]
👍

**Comment by jakebolewski** [comment]
It looks like the openssl build issues have been resolved, also in the past the sdk had issues compiling all components due to the old gcc toolchain being used, probably now that can be relaxed if required.

**Comment by pitrou** [comment]
Well, I think I only need s3 myself... @xhochy thoughts?

**Comment by jakebolewski** [comment]
@pitrou can we add you as a maintainer as well for this feedstock?  I think having more than myself would be helpful as aws releases constantly.  We used to rely on this for the tiledb conda package but had to revert to statically building the SDK for a while while some build fixes were addressed upstream as well as some API changes in the SDK. Probably now that we have synced back up to the 1.7x branch we can use this feedstock again.

**Comment by pitrou** [comment]
@jakebolewski Yes, you can add me.

**Comment by xhochy** [comment]
> Well, I think I only need s3 myself... @xhochy thoughts?

S3 is enough

**Pull request merged**
